/**
 * Rollup Configuration for Floss App IIFE Bundle
 *
 * Phase 7.3: Full Unification - One HTML Entry
 *
 * This config bundles the entire Floss app (shell + core + effects + ui)
 * into a single IIFE file for file:// compatibility.
 *
 * Entry: js/floss-app.js (shell entry point)
 * Output: js/floss-app.iife.js (IIFE bundle)
 *
 * External (loaded as globals):
 * - THREE.js (window.THREE)
 * - Coloris (window.Coloris)
 * - h264-mp4-encoder (window.HME) - loaded via separate UMD bundle
 *
 * Bundled inline:
 * - All js/core/* modules
 * - All js/effects/* modules
 * - All js/ui/* modules
 * - All js/utils/* modules
 * - lib/canvas-record/package/* (local canvas-record)
 */

import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';

export default {
    input: 'js/floss-app.js',

    output: {
        file: 'js/floss-app.iife.js',
        format: 'iife',
        name: 'FlossAppBundle',
        sourcemap: false,

        // Map external imports to globals
        globals: {
            // h264-mp4-encoder is loaded via separate UMD bundle
            // It exposes HME globally
            'h264-mp4-encoder': 'HME',

            // Optional dependencies (CDN-only, not available in file:// mode)
            // These will be undefined, but code handles this gracefully
            'gifenc': 'gifenc',
            '@ffmpeg/ffmpeg': 'FFmpeg',
            '@ffmpeg/util': 'FFmpegUtil'
        },

        // Intro: immediately expose FlossApp on window
        intro: `
// Phase 7.3: IIFE bundle generated by Rollup
// This bundle provides the same functionality as the ESM version
// Load THREE.js and Coloris before this script
`,
        // Outro: Expose FlossApp globally
        outro: `
// Expose FlossApp API on window for shell to call
if (typeof window !== 'undefined' && FlossAppBundle && FlossAppBundle.FlossApp) {
    window.FlossApp = FlossAppBundle.FlossApp;
}
`
    },

    external: [
        // h264-mp4-encoder is loaded as separate UMD bundle
        // canvas-record's H264MP4Encoder imports from 'h264-mp4-encoder'
        'h264-mp4-encoder',

        // Optional dependencies (not needed for basic MP4 export)
        // These are CDN-only and will fail gracefully if not available
        'gifenc',
        '@ffmpeg/ffmpeg',
        '@ffmpeg/util'
    ],

    plugins: [
        // Resolve node_modules and local imports
        resolve({
            browser: true,
            preferBuiltins: false
        }),

        // Convert CommonJS modules to ES6
        commonjs()
    ],

    // Suppress circular dependency warnings for internal modules
    onwarn(warning, warn) {
        // Ignore circular dependency warnings (common in large apps)
        if (warning.code === 'CIRCULAR_DEPENDENCY') return;
        warn(warning);
    }
};
